//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ColorScheme : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColorScheme defaultInstance = ((ColorScheme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColorScheme())));
        
        public static ColorScheme Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("188, 108, 37")]
        public global::System.Drawing.Color Brown1 {
            get {
                return ((global::System.Drawing.Color)(this["Brown1"]));
            }
            set {
                this["Brown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("221, 161, 94")]
        public global::System.Drawing.Color Brown2 {
            get {
                return ((global::System.Drawing.Color)(this["Brown2"]));
            }
            set {
                this["Brown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("212, 163, 115")]
        public global::System.Drawing.Color Brown3 {
            get {
                return ((global::System.Drawing.Color)(this["Brown3"]));
            }
            set {
                this["Brown3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 237, 205")]
        public global::System.Drawing.Color LightBrown1 {
            get {
                return ((global::System.Drawing.Color)(this["LightBrown1"]));
            }
            set {
                this["LightBrown1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("254, 250, 224")]
        public global::System.Drawing.Color LightBrown2 {
            get {
                return ((global::System.Drawing.Color)(this["LightBrown2"]));
            }
            set {
                this["LightBrown2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 54, 24")]
        public global::System.Drawing.Color DarkGreen1 {
            get {
                return ((global::System.Drawing.Color)(this["DarkGreen1"]));
            }
            set {
                this["DarkGreen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96, 108, 56")]
        public global::System.Drawing.Color DarkGreen2 {
            get {
                return ((global::System.Drawing.Color)(this["DarkGreen2"]));
            }
            set {
                this["DarkGreen2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 213, 174")]
        public global::System.Drawing.Color LightGreen1 {
            get {
                return ((global::System.Drawing.Color)(this["LightGreen1"]));
            }
            set {
                this["LightGreen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("233, 237, 201")]
        public global::System.Drawing.Color LightGreen2 {
            get {
                return ((global::System.Drawing.Color)(this["LightGreen2"]));
            }
            set {
                this["LightGreen2"] = value;
            }
        }
    }
}
