//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCards.lang.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий карточки на стороне:.
        /// </summary>
        public static string Card_comment_refers_to_ {
            get {
                return ResourceManager.GetString("Card comment refers to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лицевая сторона:.
        /// </summary>
        public static string Card_face_ {
            get {
                return ResourceManager.GetString("Card face:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык лицевой стороны карточки:.
        /// </summary>
        public static string Card_face_language_ {
            get {
                return ResourceManager.GetString("Card face language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточек:.
        /// </summary>
        public static string Cards_ {
            get {
                return ResourceManager.GetString("Cards:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание:.
        /// </summary>
        public static string Comment_ {
            get {
                return ResourceManager.GetString("Comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление файла.
        /// </summary>
        public static string Delete_file {
            get {
                return ResourceManager.GetString("Delete file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить стопку.
        /// </summary>
        public static string Delete_stack {
            get {
                return ResourceManager.GetString("Delete stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование стопки.
        /// </summary>
        public static string Editing_stack {
            get {
                return ResourceManager.GetString("Editing stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экпортировать стопку в файл....
        /// </summary>
        public static string Export_stack_to_file___ {
            get {
                return ResourceManager.GetString("Export stack to file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово!.
        /// </summary>
        public static string Finished_ {
            get {
                return ResourceManager.GetString("Finished!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иностраный.
        /// </summary>
        public static string Foreign {
            get {
                return ResourceManager.GetString("Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иностраный язык:.
        /// </summary>
        public static string Foreign_language_ {
            get {
                return ResourceManager.GetString("Foreign language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображения|*.jpg;*.png;*.gif|Все файлы|*.*.
        /// </summary>
        public static string Image_files___jpg___png___gif_All_files____ {
            get {
                return ResourceManager.GetString("Image files|*.jpg;*.png;*.gif|All files|*.*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать стопку из файла....
        /// </summary>
        public static string Import_stack_from_file___ {
            get {
                return ResourceManager.GetString("Import stack from file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знаю!.
        /// </summary>
        public static string Known_ {
            get {
                return ResourceManager.GetString("Known!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учить!.
        /// </summary>
        public static string Learn_ {
            get {
                return ResourceManager.GetString("Learn!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родной.
        /// </summary>
        public static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родной язык:.
        /// </summary>
        public static string Native_language_ {
            get {
                return ResourceManager.GetString("Native language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточки.
        /// </summary>
        public static string Open_cards {
            get {
                return ResourceManager.GetString("Open cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть изображение....
        /// </summary>
        public static string Open_picture___ {
            get {
                return ResourceManager.GetString("Open picture...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалено записей:.
        /// </summary>
        public static string Records_removed_ {
            get {
                return ResourceManager.GetString("Records removed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите иконку:.
        /// </summary>
        public static string Select_icon_ {
            get {
                return ResourceManager.GetString("Select icon:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стопки |*.stk|Все файлы|*.*.
        /// </summary>
        public static string Stack_files___stk_All_files____ {
            get {
                return ResourceManager.GetString("Stack files|*.stk|All files|*.*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стопки.
        /// </summary>
        public static string Stacks {
            get {
                return ResourceManager.GetString("Stacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        public static string Title_ {
            get {
                return ResourceManager.GetString("Title:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод:.
        /// </summary>
        public static string Translation_ {
            get {
                return ResourceManager.GetString("Translation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знаю!.
        /// </summary>
        public static string Unknown_ {
            get {
                return ResourceManager.GetString("Unknown!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово:.
        /// </summary>
        public static string Word_ {
            get {
                return ResourceManager.GetString("Word:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы собираетесь удалить карточку со всем её содержимым. Это действие нельзя отменить. Продолжить всё равно?.
        /// </summary>
        public static string You_re_going_to_delete_card_with_all_its_contents__This_action_can_t_be_undone__Continue_anyway_ {
            get {
                return ResourceManager.GetString("You\'re going to delete card with all its contents. This action can\'t be undone. C" +
                        "ontinue anyway?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы собираетесь удалить картинку. Это действие нельзя отменить. Продолжить всё равно? .
        /// </summary>
        public static string You_re_going_to_delete_picture__This_action_can_t_be_undone__Continue_anyway_ {
            get {
                return ResourceManager.GetString("You\'re going to delete picture. This action can\'t be undone. Continue anyway?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы собираетесь удалить стопку со всеми карточками. Это действие нельзя отменить. Продолжить всё равно?.
        /// </summary>
        public static string You_re_going_to_delete_stack_with_all_cards_in_it__This_action_can_t_be_undone__Continue_anyway_ {
            get {
                return ResourceManager.GetString("You\'re going to delete stack with all cards in it. This action can\'t be undone. C" +
                        "ontinue anyway?", resourceCulture);
            }
        }
    }
}
